import { UserGroups } from "@/constants";
const { OWNER, VETERINARIAN, ADMIN, GOVERNMENT } = UserGroups;

export const dashboardItems = [
  {
    icon: "mdi-card-account-details-star-outline",
    title: "Pet Owner",
    height: 240,
    roles: [OWNER],
    visible: true,
    soon: false,
    disabled: false,
    to: { name: "OwnerDashboard" },
  },
  // {
  //   icon: "mdi-stethoscope",
  //   title: "Veterinarian Area",
  //   height: 240,
  //   roles: [VETERINARIAN],
  //   visible: true,
  //   soon: false,
  //   disabled: false,
  // },
  // {
  //   icon: "mdi-shield-star",
  //   title: "Government",
  //   height: 240,
  //   roles: [GOVERNMENT],
  //   visible: true,
  //   soon: false,
  //   disabled: false,
  // },
  {
    icon: "mdi-magnify",
    title: "Search Pets",
    height: 240,
    roles: [OWNER, VETERINARIAN, GOVERNMENT, ADMIN],
    visible: true,
    soon: false,
    disabled: false,
    to: { name: "SearchDashboard" },
  },
  // {
  //   icon: "mdi-needle",
  //   title: "Pet Vaccination",
  //   height: 240,
  //   roles: [OWNER, VETERINARIAN, GOVERNMENT, ADMIN],
  //   visible: true,
  //   soon: true,
  //   disabled: true,
  // },
  {
    icon: "mdi-calendar",
    title: "Upcoming Events",
    height: 240,
    roles: [OWNER, VETERINARIAN, GOVERNMENT, ADMIN],
    visible: true,
    soon: true,
    disabled: true,
  },
  {
    icon: "mdi-cash",
    title: "Points and Rewards",
    height: 240,
    roles: [OWNER, VETERINARIAN, GOVERNMENT, ADMIN],
    visible: true,
    soon: true,
    disabled: true,
  },
  {
    icon: "mdi-account-network",
    title: "Admin Panel",
    height: 240,
    roles: [ADMIN],
    visible: true,
    soon: false,
    disabled: false,

    to: { name: "AdminDashboard" },
  },
];
